// apps/web/src/routes/callback/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { authState } from '$lib/auth';
	import CalmCentered from '$lib/components/home/calm-centered.svelte';

	$effect(() => {
		if (!$authState.isReady) {
			return;
		}

		void goto(resolve('/'), { replaceState: true });
	});
</script>

<svelte:head>
	<title>Signing In</title>
</svelte:head>

<CalmCentered
	title="Completing sign-in"
	description="Sprocket is finishing authentication and will return to your projects automatically."
/>

// apps/web/src/callback.tsx
import { useEffect } from 'react';
import { authState } from '$lib/auth';
import { useStore } from '$lib/store';
import CalmCentered from '$lib/components/home/calm-centered';

export default function Callback() {
	const { isReady } = useStore(authState);
	useEffect(() => {
		document.title = 'Signing In';
	}, []);
	useEffect(() => {
		if (isReady) window.location.replace('/');
	}, [isReady]);
	return (
		<CalmCentered
			title="Completing sign-in"
			description="Sprocket is finishing authentication and will return to your projects automatically."
		/>
	);
}
