// apps/web/src/lib/components/chat-markdown.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import type { ArtifactEntry } from '$lib/chat/artifacts';
	import { renderMarkdownBlocks } from '$lib/chat/markdown';
	import ArtifactReference from '$lib/components/artifact-reference.svelte';

	const NO_ARTIFACTS = new Set<string>();

	type Props = {
		content: string;
		className?: string;
		artifacts?: ArtifactEntry[];
		onOpenArtifact?: (artifactId: string) => void;
		openLinksInNewTab?: boolean;
	};

	let {
		content,
		className = '',
		artifacts = [],
		onOpenArtifact,
		openLinksInNewTab = false
	}: Props = $props();

	const artifactById = $derived(new Map(artifacts.map((artifact) => [artifact.key, artifact])));
	const blocks = $derived(
		renderMarkdownBlocks(
			content,
			onOpenArtifact ? new Set(artifactById.keys()) : NO_ARTIFACTS,
			openLinksInNewTab
		)
	);
</script>

<div class={cn('chat-markdown', className)}>
	{#each blocks as block, index (`${block.type}-${index}`)}
		{#if block.type === 'artifact'}
			{@const artifact = artifactById.get(block.artifactId)}
			{#if artifact && onOpenArtifact}
				<ArtifactReference {artifact} onOpen={() => onOpenArtifact(block.artifactId)} />
			{/if}
		{:else}
			<!-- eslint-disable-next-line svelte/no-at-html-tags -->
			{@html block.html}
		{/if}
	{/each}
</div>

// apps/web/src/lib/components/chat-markdown.tsx
import { useMemo } from 'react';
import { cn } from '$lib/utils';
import type { ArtifactEntry } from '$lib/chat/artifacts';
import { renderMarkdownBlocks } from '$lib/chat/markdown';
import ArtifactReference from '$lib/components/artifact-reference';
import MarkdownHtml from '$lib/components/markdown-html';

const NO_ARTIFACTS = new Set<string>();

export default function ChatMarkdown({
	content,
	className = '',
	artifacts = [],
	onOpenArtifact,
	openLinksInNewTab = false
}: {
	content: string;
	className?: string;
	artifacts?: ArtifactEntry[];
	onOpenArtifact?: (artifactId: string) => void;
	openLinksInNewTab?: boolean;
}) {
	const artifactById = useMemo(
		() => new Map(artifacts.map((artifact) => [artifact.key, artifact])),
		[artifacts]
	);

	const blocks = useMemo(
		() =>
			renderMarkdownBlocks(
				content,
				onOpenArtifact ? new Set(artifactById.keys()) : NO_ARTIFACTS,
				openLinksInNewTab
			),
		[content, onOpenArtifact, artifactById, openLinksInNewTab]
	);

	return (
		<div className={cn('chat-markdown', className)}>
			{blocks.map((block, index) => {
				if (block.type === 'artifact') {
					const artifact = artifactById.get(block.artifactId);

					if (artifact && onOpenArtifact) {
						return (
							<ArtifactReference
								key={`${block.type}-${index}`}
								artifact={artifact}
								onOpen={() => onOpenArtifact(block.artifactId)}
							/>
						);
					}

					return null;
				}

				return <MarkdownHtml key={`${block.type}-${index}`} html={block.html} />;
			})}
		</div>
	);
}
