// apps/web/src/lib/components/home/inbox-load-more.svelte
<script lang="ts">
	import type { InboxSectionData } from '$lib/project/inbox.svelte';

	let { section }: { section: InboxSectionData } = $props();
</script>

<div class="inbox-load-more" aria-live="polite">
	{#if section.error}
		<span role="alert">{section.error}</span>
	{:else if section.loading}
		<span>Loading...</span>
	{:else if section.canLoadMore}
		<button type="button" onclick={section.loadMore}>Show more</button>
	{/if}
</div>

// apps/web/src/lib/components/home/inbox-load-more.tsx
import type { InboxSectionData } from '$lib/project/inbox';

export default function InboxLoadMore({ section }: { section: InboxSectionData }) {
	return (
		<div className="inbox-load-more" aria-live="polite">
			{section.error ? (
				<span role="alert">{section.error}</span>
			) : section.loading ? (
				<span>Loading...</span>
			) : section.canLoadMore ? (
				<button type="button" onClick={section.loadMore}>
					Show more
				</button>
			) : null}
		</div>
	);
}
