// apps/web/src/lib/components/home/inbox-sidebar.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import {
	Check,
	ChevronDown,
	Copy,
	FolderPlus,
	RotateCcw,
	Search,
	Settings,
	SquarePen,
	X
} from 'lucide-react';
import type {
	DragEvent as ReactDragEvent,
	KeyboardEvent as ReactKeyboardEvent,
	MouseEvent as ReactMouseEvent
} from 'react';
import type { Doc, Id } from '$convex/_generated/dataModel';
import type { CatalogModel } from '$convex/lib/uiModelCatalog';
import { inboxState, type InboxState } from '$convex/lib/inboxState';
import type { Project } from '$lib/types/sprocket';
import type { SprocketTheme } from '$lib/theme';
import type { InboxSectionData } from '$lib/project/inbox';
import BrandMark from '$lib/components/brand-mark';
import ProviderLogo from '$lib/components/provider-logo';
import AppUpdate from './app-update';
import InboxLoadMore from './inbox-load-more';
import SidebarTopActions from './sidebar-top-actions';

const SETTLED_INBOX_OPEN_KEY = 'sprocket.inbox.settled-open';

type Thread = Doc<'threadRecords'>;

const labels = {
	unsettled: 'Unsettled',
	settled: 'Settled Threads'
} satisfies Record<InboxState, string>;

export default function InboxSidebar({
	sections,
	projects,
	models,
	selectedProjects,
	currentThreadId,
	settledOpen = false,
	onSettledOpenChange,
	mutationsEnabled,
	theme,
	onThemeChange,
	onFilter,
	onSelect,
	onNew,
	onAddProject,
	onSettings,
	onClose,
	onChange,
	onRename
}: {
	sections: InboxSectionData[];
	projects: Project[];
	models: readonly Pick<CatalogModel, 'id' | 'label' | 'provider'>[];
	selectedProjects: string[];
	currentThreadId: Id<'threadRecords'> | null;
	settledOpen?: boolean;
	onSettledOpenChange: (open: boolean) => void;
	mutationsEnabled: boolean;
	theme: SprocketTheme;
	onThemeChange: (theme: SprocketTheme) => void;
	onFilter: (keys: string[]) => void;
	onSelect: (thread: Thread) => void;
	onNew: () => void;
	onAddProject: () => void;
	onSettings: () => void;
	onClose: () => void;
	onChange: (thread: Thread, state: InboxState) => Promise<void>;
	onRename: (thread: Thread, title: string) => Promise<void>;
}) {
	const [dragging, setDragging] = useState<Thread | null>(null);
	const [menu, setMenu] = useState<{ thread: Thread; x: number; y: number } | null>(null);
	const [notice, setNotice] = useState<string | null>(null);
	const [busy, setBusy] = useState(false);
	const [renameThread, setRenameThread] = useState<Thread | null>(null);
	const [renameTitle, setRenameTitle] = useState('');
	const [now, setNow] = useState(() => Date.now());
	const [projectSearch, setProjectSearch] = useState('');
	const busyRef = useRef(false);
	const menuTriggerRef = useRef<HTMLElement | null>(null);
	const renameInputRef = useRef<HTMLInputElement | null>(null);
	const projectMenuRef = useRef<HTMLDetailsElement | null>(null);
	const onSettledOpenChangeRef = useRef(onSettledOpenChange);

	const closeMenu = useCallback(() => {
		const trigger = menuTriggerRef.current;
		menuTriggerRef.current = null;
		setMenu(null);
		trigger?.focus();
	}, []);

	const rows = sections.flatMap((section) => section.rows);
	const filteredProjects = projects.filter((project) =>
		project.displayName.toLocaleLowerCase().includes(projectSearch.trim().toLocaleLowerCase())
	);
	const visibleSections = sections.filter(
		(section) =>
			section.rows.length ||
			section.loading ||
			section.error ||
			section.canLoadMore ||
			(section.state === 'settled' && !settledOpen)
	);
	const projectFilterLabel =
		selectedProjects.length === 0
			? 'All projects'
			: selectedProjects.length === 1
				? (projects.find((project) => project.repositoryKey === selectedProjects[0])
						?.displayName ?? 'All projects')
				: `${selectedProjects.length} projects`;
	const menuThread = menu?.thread ?? null;

	useEffect(() => {
		onSettledOpenChangeRef.current = onSettledOpenChange;
	});

	useEffect(() => {
		try {
			const savedSettledOpen = localStorage.getItem(SETTLED_INBOX_OPEN_KEY);
			if (savedSettledOpen !== null) {
				onSettledOpenChangeRef.current(savedSettledOpen === 'true');
			}
		} catch {
			// Browsers can deny storage access while still allowing the app to run.
		}
		const timer = setInterval(() => {
			setNow(Date.now());
		}, 30_000);
		return () => clearInterval(timer);
	}, []);

	useEffect(() => {
		if (!renameThread || !renameInputRef.current) return;
		renameInputRef.current.focus();
		renameInputRef.current.select();
	}, [renameThread]);

	useEffect(() => {
		if (!menu) return;
		document
			.querySelector<HTMLButtonElement>('.inbox-context-menu button:not(:disabled)')
			?.focus();
	}, [menu]);

	function projectName(thread: Thread) {
		return (
			projects.find((project) => project.repositoryKey === thread.repositoryKey)?.displayName ??
			thread.repositoryKey
		);
	}

	function threadModel(thread: Thread) {
		return models.find((model) => model.id === thread.selectedModel);
	}

	function closeProjectMenu() {
		if (projectMenuRef.current) {
			projectMenuRef.current.open = false;
		}
		setProjectSearch('');
	}

	function filterProjects(keys: string[]) {
		onFilter(keys);
		closeProjectMenu();
	}

	function addProject() {
		closeProjectMenu();
		onAddProject();
	}

	function toggleSettled() {
		const next = !settledOpen;
		onSettledOpenChange(next);
		try {
			localStorage.setItem(SETTLED_INBOX_OPEN_KEY, String(next));
		} catch {
			// The collapsed state still works for this session without storage.
		}
	}

	function age(at: number) {
		const minutes = Math.max(0, Math.floor((now - at) / 60_000));
		if (minutes < 1) return 'now';
		if (minutes < 60) return `${minutes}m`;
		if (minutes < 1440) return `${Math.floor(minutes / 60)}h`;
		return `${Math.floor(minutes / 1440)}d`;
	}

	function runStatus(thread: Thread) {
		if (thread.status === 'queued') return 'Starting';
		if (thread.status === 'running') return 'Working';
		return thread.status === 'failed' ? 'Failed' : null;
	}

	function choose(thread: Thread) {
		onSelect(thread);
	}

	function beginRename(thread: Thread) {
		setMenu(null);
		setRenameThread(thread);
		setRenameTitle(thread.title ?? '');
	}

	function cancelRename() {
		setRenameThread(null);
		setRenameTitle('');
	}

	async function commitRename() {
		if (!renameThread) return;
		const thread = renameThread;
		const title = renameTitle.trim();
		if (!title || title === (thread.title ?? '')) {
			cancelRename();
			return;
		}
		cancelRename();
		try {
			await onRename(thread, title);
		} catch (error) {
			setNotice(error instanceof Error ? error.message : 'Could not rename thread.');
		}
	}

	function canChange(thread: Thread, state: InboxState) {
		return inboxState(thread) !== state && (state !== 'settled' || thread.status !== 'running');
	}

	async function change(thread: Thread, state: InboxState) {
		if (!mutationsEnabled || busyRef.current) return;
		closeMenu();
		busyRef.current = true;
		setBusy(true);
		setNotice(null);
		if (!canChange(thread, state)) {
			busyRef.current = false;
			setBusy(false);
			return;
		}
		try {
			await onChange(thread, state);
		} catch (error) {
			setNotice(error instanceof Error ? error.message : 'Could not update thread.');
		} finally {
			busyRef.current = false;
			setBusy(false);
		}
	}

	function canDrop(state: InboxState) {
		return mutationsEnabled && !busy && dragging !== null && canChange(dragging, state);
	}

	function dropThreads(event: ReactDragEvent, state: InboxState) {
		event.preventDefault();
		if (dragging && canDrop(state)) void change(dragging, state);
		setDragging(null);
	}

	function openMenu(event: ReactMouseEvent, thread: Thread) {
		event.preventDefault();
		const trigger = event.currentTarget instanceof HTMLElement ? event.currentTarget : null;
		menuTriggerRef.current = trigger;
		const rect = trigger?.getBoundingClientRect();
		const pointerX = event.clientX;
		const pointerY = event.clientY;
		setMenu({
			thread,
			x: Math.min(pointerX || rect?.left || 8, window.innerWidth - 230),
			y: Math.min(pointerY || rect?.bottom || 8, window.innerHeight - 260)
		});
	}

	function navigateMenu(event: ReactKeyboardEvent<HTMLDivElement>) {
		if (event.key === 'Tab' || event.key === 'Escape') {
			event.preventDefault();
			closeMenu();
			return;
		}
		if (!['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return;
		event.preventDefault();
		const buttons = [
			...event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')
		];
		const index = buttons.findIndex((button) => button === document.activeElement);
		const next =
			event.key === 'Home'
				? 0
				: event.key === 'End'
					? buttons.length - 1
					: (index + (event.key === 'ArrowUp' ? -1 : 1) + buttons.length) % buttons.length;
		buttons[next]?.focus();
	}

	const handleWindowKeydown = useCallback(
		(event: KeyboardEvent) => {
			if (event.defaultPrevented) return;
			if (event.key === 'Escape') {
				if (menu) closeMenu();
				return;
			}
			if (event.altKey && event.key.toLowerCase() === 'n') {
				event.preventDefault();
				onNew();
			}
			if (
				event.target instanceof Element &&
				event.target.closest('input, textarea, [contenteditable="true"], dialog')
			)
				return;
			if (event.altKey && ['ArrowUp', 'ArrowDown'].includes(event.key)) {
				const index = rows.findIndex((thread) => thread._id === currentThreadId);
				const row = rows[index + (event.key === 'ArrowDown' ? 1 : -1)];
				if (row) {
					event.preventDefault();
					onSelect(row);
				}
			}
		},
		[menu, closeMenu, onNew, rows, currentThreadId, onSelect]
	);

	useEffect(() => {
		window.addEventListener('keydown', handleWindowKeydown);
		return () => window.removeEventListener('keydown', handleWindowKeydown);
	}, [handleWindowKeydown]);

	return (
		<aside className="inbox-sidebar" aria-label="Thread inbox">
			<header className="flex items-center gap-2 px-4 pt-4 pb-3">
				<BrandMark size="sm" class="mr-auto" label="Close sidebar" onclick={() => onClose()} />
				<SidebarTopActions theme={theme} onThemeChange={onThemeChange} onClose={onClose} />
			</header>

			<div className="px-3 pb-3">
				<button className="inbox-menu-item inbox-primary-navigation" type="button" onClick={onNew}>
					<SquarePen size={15} />New thread
				</button>
				<div className="inbox-project-controls">
					<details ref={projectMenuRef}>
						<summary className="inbox-filter inbox-primary-navigation">
							<span className="truncate">{projectFilterLabel}</span>
							<ChevronDown size={14} />
						</summary>
						<div className="inbox-project-menu">
							<label className="inbox-project-search">
								<Search size={14} />
								<input
									value={projectSearch}
									onChange={(event) => setProjectSearch(event.currentTarget.value)}
									aria-label="Search projects"
									placeholder="Search projects"
								/>
							</label>
							<div className="inbox-project-list">
								<button
									className={`inbox-project-option${selectedProjects.length === 0 ? ' inbox-project-selected' : ''}`}
									type="button"
									aria-pressed={selectedProjects.length === 0}
									onClick={() => filterProjects([])}
								>
									All projects
								</button>
								{filteredProjects.map((project) => {
									const selected =
										selectedProjects.length === 1 &&
										selectedProjects[0] === project.repositoryKey;
									return (
										<button
											key={project.repositoryKey}
											className={`inbox-project-option${selected ? ' inbox-project-selected' : ''}`}
											type="button"
											aria-pressed={selected}
											onClick={() => filterProjects([project.repositoryKey])}
										>
											{project.displayName}
										</button>
									);
								})}
							</div>
						</div>
					</details>
					<button
						className="inbox-icon inbox-add-project-button"
						type="button"
						aria-label="Create or add project"
						onClick={addProject}
					>
						<FolderPlus size={17} />
					</button>
				</div>
			</div>

			<div className="inbox-scroll">
				{visibleSections.map((section) => (
					<section
						key={section.state}
						id={`inbox-${section.state}`}
						onDragOver={(event) => {
							if (canDrop(section.state)) event.preventDefault();
						}}
						onDrop={(event) => dropThreads(event, section.state)}
						aria-label={labels[section.state]}
					>
						{section.state === 'settled' && (
							<button
								className="inbox-section-heading inbox-primary-navigation"
								type="button"
								aria-expanded={settledOpen}
								aria-controls="inbox-settled-threads"
								onClick={toggleSettled}
							>
								<span>Settled Threads</span>
								<ChevronDown
									className={settledOpen ? 'inbox-section-chevron-open' : undefined}
									size={14}
								/>
							</button>
						)}
						<div id={section.state === 'settled' ? 'inbox-settled-threads' : undefined}>
							{(section.state !== 'settled' || settledOpen) && (
								<>
									{section.rows.map((thread) => {
										const stateLabel = runStatus(thread);
										const model = threadModel(thread);
										const isRenaming = renameThread?._id === thread._id;
										return (
											<div
												key={thread._id}
												className={`inbox-row${thread._id === currentThreadId ? ' inbox-row-selected' : ''}`}
												draggable={mutationsEnabled && !busy && !isRenaming}
												onDragStart={(event) => {
													setDragging(thread);
													event.dataTransfer?.setData('text/plain', thread._id);
												}}
												onDragEnd={() => setDragging(null)}
												onContextMenu={(event) => openMenu(event, thread)}
												role="group"
												aria-label={thread.title ?? 'New thread'}
											>
												{isRenaming ? (
													<form
														className="inbox-row-main"
														onSubmit={(event) => {
															event.preventDefault();
															void commitRename();
														}}
													>
														<span className="inbox-row-meta">
															<span className="truncate">{projectName(thread)}</span>
															<span className="inbox-row-age shrink-0">
																{age(thread.lastMessageAt)}
															</span>
														</span>
														<input
															ref={renameInputRef}
															value={renameTitle}
															onChange={(event) => setRenameTitle(event.currentTarget.value)}
															className="inbox-row-rename-input"
															aria-label="Rename thread"
															maxLength={300}
															onKeyDown={(event) => {
																if (event.key !== 'Escape') return;
																event.preventDefault();
																cancelRename();
															}}
															onBlur={() => void commitRename()}
														/>
														<span className="inbox-row-model">
															{model ? (
																<>
																	<ProviderLogo
																		provider={model.provider}
																		className="size-3.5 shrink-0"
																	/>
																	<span className="truncate">{model.label}</span>
																</>
															) : (
																<span className="truncate">Unknown model</span>
															)}
														</span>
													</form>
												) : (
													<button
														className="inbox-row-main"
														type="button"
														title={`${thread.title ?? 'New thread'}\n${projectName(thread)}\n${new Date(thread.lastMessageAt).toLocaleString()}`}
														onClick={() => choose(thread)}
														onDoubleClick={() => {
															if (!mutationsEnabled || busy) return;
															beginRename(thread);
														}}
														aria-current={thread._id === currentThreadId ? 'page' : undefined}
													>
														<span className="inbox-row-meta">
															<span className="truncate">{projectName(thread)}</span>
															<span className="inbox-row-age shrink-0">
																{age(thread.lastMessageAt)}
															</span>
														</span>
														<span className="inbox-row-title truncate">
															{thread.title ?? 'New thread'}
														</span>
														<span className="inbox-row-model">
															{model ? (
																<>
																	<ProviderLogo
																		provider={model.provider}
																		className="size-3.5 shrink-0"
																	/>
																	<span className="truncate">{model.label}</span>
																</>
															) : (
																<span className="truncate">Unknown model</span>
															)}
															{stateLabel && (
																<span
																	className={`inbox-status${
																		thread.status === 'queued' || thread.status === 'running'
																			? ' inbox-working'
																			: ''
																	}${thread.status === 'failed' ? ' inbox-attention' : ''}`}
																>
																	{stateLabel}
																</span>
															)}
														</span>
													</button>
												)}
												{!isRenaming && (
													<div className="inbox-row-actions">
														{section.state === 'unsettled' ? (
															<button
																className="inbox-icon inbox-row-state-action"
																type="button"
																disabled={!mutationsEnabled || busy || !canChange(thread, 'settled')}
																aria-label={`Settle ${thread.title ?? 'thread'}`}
																data-tooltip="Settle"
																onClick={() => void change(thread, 'settled')}
															>
																<Check size={14} />
															</button>
														) : (
															<button
																className="inbox-icon inbox-row-state-action"
																type="button"
																disabled={!mutationsEnabled || busy}
																aria-label={`Unsettle ${thread.title ?? 'thread'}`}
																data-tooltip="Unsettle"
																onClick={() => void change(thread, 'unsettled')}
															>
																<RotateCcw size={14} />
															</button>
														)}
													</div>
												)}
											</div>
										);
									})}
									<InboxLoadMore section={section} />
								</>
							)}
						</div>
					</section>
				))}
			</div>

			{notice && (
				<div className="inbox-notice" role="status">
					<span>{notice}</span>
					<button
						type="button"
						aria-label="Dismiss notification"
						onClick={() => setNotice(null)}
					>
						<X size={13} />
					</button>
				</div>
			)}

			<footer className="inbox-footer">
				<button className="inbox-menu-item inbox-primary-navigation" type="button" onClick={onSettings}>
					<Settings size={15} />Settings
				</button>
				<AppUpdate />
			</footer>

			{menu && menuThread && (
				<>
					<button
						className="fixed inset-0 z-[200] cursor-default"
						type="button"
						aria-label="Close thread actions"
						onClick={closeMenu}
					></button>
					<div
						className="inbox-context-menu"
						style={{ left: `${Math.max(8, menu.x)}px`, top: `${Math.max(8, menu.y)}px` }}
						role="menu"
						tabIndex={-1}
						onKeyDown={navigateMenu}
					>
						{inboxState(menuThread) === 'unsettled' ? (
							<button
								type="button"
								role="menuitem"
								disabled={!mutationsEnabled || busy || !canChange(menuThread, 'settled')}
								onClick={() => void change(menuThread, 'settled')}
							>
								<Check size={14} />
								Settle
							</button>
						) : (
							<button
								type="button"
								role="menuitem"
								disabled={!mutationsEnabled || busy}
								onClick={() => void change(menuThread, 'unsettled')}
							>
								<RotateCcw size={14} />
								Unsettle
							</button>
						)}
						<button
							type="button"
							role="menuitem"
							disabled={!mutationsEnabled}
							onClick={() => beginRename(menuThread)}
						>
							<SquarePen size={14} />
							Rename
						</button>
						<button
							type="button"
							role="menuitem"
							onClick={() => {
								void navigator.clipboard.writeText(menuThread._id).catch(() => {
									setNotice('Could not copy thread ID.');
								});
								setMenu(null);
							}}
						>
							<Copy size={14} />
							Copy thread ID
						</button>
					</div>
				</>
			)}
		</aside>
	);
}

// apps/web/src/lib/components/home/inbox-sidebar.svelte
<script lang="ts">
	import { onMount, tick } from 'svelte';
	import {
		Check,
		ChevronDown,
		Copy,
		FolderPlus,
		RotateCcw,
		Search,
		Settings,
		SquarePen,
		X
	} from '@lucide/svelte';
	import type { Doc, Id } from '$convex/_generated/dataModel';
	import type { CatalogModel } from '$convex/lib/uiModelCatalog';
	import { inboxState, type InboxState } from '$convex/lib/inboxState';
	import type { Project } from '$lib/types/sprocket';
	import type { SprocketTheme } from '$lib/theme';
	import type { InboxSectionData } from '$lib/project/inbox.svelte';
	import BrandMark from '$lib/components/brand-mark.svelte';
	import ProviderLogo from '$lib/components/provider-logo.svelte';
	import AppUpdate from './app-update.svelte';
	import InboxLoadMore from './inbox-load-more.svelte';
	import SidebarTopActions from './sidebar-top-actions.svelte';

	const SETTLED_INBOX_OPEN_KEY = 'sprocket.inbox.settled-open';

	type Thread = Doc<'threadRecords'>;
	type Props = {
		sections: InboxSectionData[];
		projects: Project[];
		models: readonly Pick<CatalogModel, 'id' | 'label' | 'provider'>[];
		selectedProjects: string[];
		currentThreadId: Id<'threadRecords'> | null;
		settledOpen?: boolean;
		mutationsEnabled: boolean;
		theme: SprocketTheme;
		onThemeChange: (theme: SprocketTheme) => void;
		onFilter: (keys: string[]) => void;
		onSelect: (thread: Thread) => void;
		onNew: () => void;
		onAddProject: () => void;
		onSettings: () => void;
		onClose: () => void;
		onChange: (thread: Thread, state: InboxState) => Promise<void>;
		onRename: (thread: Thread, title: string) => Promise<void>;
	};

	let {
		sections,
		projects,
		models,
		selectedProjects,
		currentThreadId,
		settledOpen = $bindable(false),
		mutationsEnabled,
		theme,
		onThemeChange,
		onFilter,
		onSelect,
		onNew,
		onAddProject,
		onSettings,
		onClose,
		onChange,
		onRename
	}: Props = $props();

	const labels = {
		unsettled: 'Unsettled',
		settled: 'Settled Threads'
	} satisfies Record<InboxState, string>;
	let dragging = $state<Thread | null>(null);
	let menu = $state<{ thread: Thread; x: number; y: number } | null>(null);
	let menuTrigger: HTMLElement | null = null;
	let notice = $state<string | null>(null);
	let busy = $state(false);
	let renameThread = $state<Thread | null>(null);
	let renameTitle = $state('');
	let renameInput = $state<HTMLInputElement | null>(null);
	let now = $state(Date.now());
	let projectMenuOpen = $state(false);
	let projectSearch = $state('');
	const rows = $derived(sections.flatMap((section) => section.rows));
	const filteredProjects = $derived(
		projects.filter((project) =>
			project.displayName.toLocaleLowerCase().includes(projectSearch.trim().toLocaleLowerCase())
		)
	);
	const visibleSections = $derived(
		sections.filter(
			(section) =>
				section.rows.length ||
				section.loading ||
				section.error ||
				section.canLoadMore ||
				(section.state === 'settled' && !settledOpen)
		)
	);
	const projectFilterLabel = $derived(
		selectedProjects.length === 0
			? 'All projects'
			: selectedProjects.length === 1
				? (projects.find((project) => project.repositoryKey === selectedProjects[0])?.displayName ??
					'All projects')
				: `${selectedProjects.length} projects`
	);

	onMount(() => {
		try {
			const savedSettledOpen = localStorage.getItem(SETTLED_INBOX_OPEN_KEY);
			if (savedSettledOpen !== null) settledOpen = savedSettledOpen === 'true';
		} catch {
			// Browsers can deny storage access while still allowing the app to run.
		}
		const timer = setInterval(() => {
			now = Date.now();
		}, 30_000);
		return () => clearInterval(timer);
	});

	$effect(() => {
		if (!renameThread || !renameInput) return;
		renameInput.focus();
		renameInput.select();
	});

	function projectName(thread: Thread) {
		return (
			projects.find((project) => project.repositoryKey === thread.repositoryKey)?.displayName ??
			thread.repositoryKey
		);
	}

	function threadModel(thread: Thread) {
		return models.find((model) => model.id === thread.selectedModel);
	}

	function filterProjects(keys: string[]) {
		onFilter(keys);
		projectMenuOpen = false;
		projectSearch = '';
	}

	function addProject() {
		projectMenuOpen = false;
		projectSearch = '';
		onAddProject();
	}

	function toggleSettled() {
		settledOpen = !settledOpen;
		try {
			localStorage.setItem(SETTLED_INBOX_OPEN_KEY, String(settledOpen));
		} catch {
			// The collapsed state still works for this session without storage.
		}
	}

	function age(at: number) {
		const minutes = Math.max(0, Math.floor((now - at) / 60_000));
		if (minutes < 1) return 'now';
		if (minutes < 60) return `${minutes}m`;
		if (minutes < 1440) return `${Math.floor(minutes / 60)}h`;
		return `${Math.floor(minutes / 1440)}d`;
	}

	function runStatus(thread: Thread) {
		if (thread.status === 'queued') return 'Starting';
		if (thread.status === 'running') return 'Working';
		return thread.status === 'failed' ? 'Failed' : null;
	}

	function choose(thread: Thread) {
		onSelect(thread);
	}

	function beginRename(thread: Thread) {
		menu = null;
		renameThread = thread;
		renameTitle = thread.title ?? '';
	}

	function cancelRename() {
		renameThread = null;
		renameTitle = '';
	}

	async function commitRename() {
		if (!renameThread) return;
		const thread = renameThread;
		const title = renameTitle.trim();
		if (!title || title === (thread.title ?? '')) {
			cancelRename();
			return;
		}
		cancelRename();
		try {
			await onRename(thread, title);
		} catch (error) {
			notice = error instanceof Error ? error.message : 'Could not rename thread.';
		}
	}

	function canChange(thread: Thread, state: InboxState) {
		return inboxState(thread) !== state && (state !== 'settled' || thread.status !== 'running');
	}

	async function change(thread: Thread, state: InboxState) {
		if (!mutationsEnabled || busy) return;
		closeMenu();
		busy = true;
		notice = null;
		if (!canChange(thread, state)) {
			busy = false;
			return;
		}
		try {
			await onChange(thread, state);
		} catch (error) {
			notice = error instanceof Error ? error.message : 'Could not update thread.';
		} finally {
			busy = false;
		}
	}

	function canDrop(state: InboxState) {
		return mutationsEnabled && !busy && dragging !== null && canChange(dragging, state);
	}

	function dropThreads(event: DragEvent, state: InboxState) {
		event.preventDefault();
		if (dragging && canDrop(state)) void change(dragging, state);
		dragging = null;
	}

	function closeMenu() {
		const trigger = menuTrigger;
		menu = null;
		menuTrigger = null;
		trigger?.focus();
	}

	function openMenu(event: MouseEvent, thread: Thread) {
		event.preventDefault();
		menuTrigger = event.currentTarget instanceof HTMLElement ? event.currentTarget : null;
		const rect = menuTrigger?.getBoundingClientRect();
		const pointerX = event instanceof MouseEvent ? event.clientX : 0;
		const pointerY = event instanceof MouseEvent ? event.clientY : 0;
		menu = {
			thread,
			x: Math.min(pointerX || rect?.left || 8, window.innerWidth - 230),
			y: Math.min(pointerY || rect?.bottom || 8, window.innerHeight - 260)
		};
		void tick().then(() =>
			document
				.querySelector<HTMLButtonElement>('.inbox-context-menu button:not(:disabled)')
				?.focus()
		);
	}

	function navigateMenu(event: KeyboardEvent) {
		if (event.key === 'Tab' || event.key === 'Escape') {
			event.preventDefault();
			closeMenu();
			return;
		}
		if (!['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return;
		event.preventDefault();
		if (!(event.currentTarget instanceof HTMLElement)) return;
		const buttons = [
			...event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')
		];
		const index = buttons.findIndex((button) => button === document.activeElement);
		const next =
			event.key === 'Home'
				? 0
				: event.key === 'End'
					? buttons.length - 1
					: (index + (event.key === 'ArrowUp' ? -1 : 1) + buttons.length) % buttons.length;
		buttons[next]?.focus();
	}

	function keydown(event: KeyboardEvent) {
		if (event.defaultPrevented) return;
		if (event.key === 'Escape') {
			if (menu) closeMenu();
			return;
		}
		if (event.altKey && event.key.toLowerCase() === 'n') {
			event.preventDefault();
			onNew();
		}
		if (
			event.target instanceof Element &&
			event.target.closest('input, textarea, [contenteditable="true"], dialog')
		)
			return;
		if (event.altKey && ['ArrowUp', 'ArrowDown'].includes(event.key)) {
			const index = rows.findIndex((thread) => thread._id === currentThreadId);
			const row = rows[index + (event.key === 'ArrowDown' ? 1 : -1)];
			if (row) {
				event.preventDefault();
				onSelect(row);
			}
		}
	}
</script>

<svelte:window onkeydown={keydown} />

<aside class="inbox-sidebar" aria-label="Thread inbox">
	<header class="flex items-center gap-2 px-4 pt-4 pb-3">
		<BrandMark size="sm" class="mr-auto" label="Close sidebar" onclick={() => onClose()} />
		<SidebarTopActions {theme} {onThemeChange} {onClose} />
	</header>

	<div class="px-3 pb-3">
		<button class="inbox-menu-item inbox-primary-navigation" type="button" onclick={onNew}>
			<SquarePen size={15} />New thread
		</button>
		<div class="inbox-project-controls">
			<details bind:open={projectMenuOpen}>
				<summary class="inbox-filter inbox-primary-navigation">
					<span class="truncate">{projectFilterLabel}</span>
					<ChevronDown size={14} />
				</summary>
				<div class="inbox-project-menu">
					<label class="inbox-project-search">
						<Search size={14} />
						<input
							bind:value={projectSearch}
							aria-label="Search projects"
							placeholder="Search projects"
						/>
					</label>
					<div class="inbox-project-list">
						<button
							class:inbox-project-selected={selectedProjects.length === 0}
							class="inbox-project-option"
							type="button"
							aria-pressed={selectedProjects.length === 0}
							onclick={() => filterProjects([])}>All projects</button
						>
						{#each filteredProjects as project (project.repositoryKey)}
							<button
								class:inbox-project-selected={selectedProjects.length === 1 &&
									selectedProjects[0] === project.repositoryKey}
								class="inbox-project-option"
								type="button"
								aria-pressed={selectedProjects.length === 1 &&
									selectedProjects[0] === project.repositoryKey}
								onclick={() => filterProjects([project.repositoryKey])}
								>{project.displayName}</button
							>
						{/each}
					</div>
				</div>
			</details>
			<button
				class="inbox-icon inbox-add-project-button"
				type="button"
				aria-label="Create or add project"
				onclick={addProject}
			>
				<FolderPlus size={17} />
			</button>
		</div>
	</div>

	<div class="inbox-scroll">
		{#each visibleSections as section (section.state)}
			<section
				id={`inbox-${section.state}`}
				ondragover={(event) => {
					if (canDrop(section.state)) event.preventDefault();
				}}
				ondrop={(event) => dropThreads(event, section.state)}
				aria-label={labels[section.state]}
			>
				{#if section.state === 'settled'}
					<button
						class="inbox-section-heading inbox-primary-navigation"
						type="button"
						aria-expanded={settledOpen}
						aria-controls="inbox-settled-threads"
						onclick={toggleSettled}
					>
						<span>Settled Threads</span>
						<ChevronDown class={settledOpen ? 'inbox-section-chevron-open' : undefined} size={14} />
					</button>
				{/if}
				<div id={section.state === 'settled' ? 'inbox-settled-threads' : undefined}>
					{#if section.state !== 'settled' || settledOpen}
						{#each section.rows as thread (thread._id)}
							{@const stateLabel = runStatus(thread)}
							{@const model = threadModel(thread)}
							{@const isRenaming = renameThread?._id === thread._id}
							<div
								class:inbox-row-selected={thread._id === currentThreadId}
								class="inbox-row"
								draggable={mutationsEnabled && !busy && !isRenaming}
								ondragstart={(event) => {
									dragging = thread;
									event.dataTransfer?.setData('text/plain', thread._id);
								}}
								ondragend={() => (dragging = null)}
								oncontextmenu={(event) => openMenu(event, thread)}
								role="group"
								aria-label={thread.title ?? 'New thread'}
							>
								{#if isRenaming}
									<form
										class="inbox-row-main"
										onsubmit={(event) => {
											event.preventDefault();
											void commitRename();
										}}
									>
										<span class="inbox-row-meta">
											<span class="truncate">{projectName(thread)}</span>
											<span class="inbox-row-age shrink-0">{age(thread.lastMessageAt)}</span>
										</span>
										<input
											bind:this={renameInput}
											bind:value={renameTitle}
											class="inbox-row-rename-input"
											aria-label="Rename thread"
											maxlength="300"
											onkeydown={(event) => {
												if (event.key !== 'Escape') return;
												event.preventDefault();
												cancelRename();
											}}
											onblur={() => void commitRename()}
										/>
										<span class="inbox-row-model">
											{#if model}
												<ProviderLogo provider={model.provider} className="size-3.5 shrink-0" />
												<span class="truncate">{model.label}</span>
											{:else}
												<span class="truncate">Unknown model</span>
											{/if}
										</span>
									</form>
								{:else}
									<button
										class="inbox-row-main"
										type="button"
										title={`${thread.title ?? 'New thread'}\n${projectName(thread)}\n${new Date(thread.lastMessageAt).toLocaleString()}`}
										onclick={() => choose(thread)}
										ondblclick={() => {
											if (!mutationsEnabled || busy) return;
											beginRename(thread);
										}}
										aria-current={thread._id === currentThreadId ? 'page' : undefined}
									>
										<span class="inbox-row-meta">
											<span class="truncate">{projectName(thread)}</span>
											<span class="inbox-row-age shrink-0">{age(thread.lastMessageAt)}</span>
										</span>
										<span class="inbox-row-title truncate">{thread.title ?? 'New thread'}</span>
										<span class="inbox-row-model">
											{#if model}
												<ProviderLogo provider={model.provider} className="size-3.5 shrink-0" />
												<span class="truncate">{model.label}</span>
											{:else}
												<span class="truncate">Unknown model</span>
											{/if}
											{#if stateLabel}
												<span
													class:inbox-working={thread.status === 'queued' ||
														thread.status === 'running'}
													class:inbox-attention={thread.status === 'failed'}
													class="inbox-status">{stateLabel}</span
												>
											{/if}
										</span>
									</button>
								{/if}
								{#if !isRenaming}<div class="inbox-row-actions">
										{#if section.state === 'unsettled'}
											<button
												class="inbox-icon inbox-row-state-action"
												type="button"
												disabled={!mutationsEnabled || busy || !canChange(thread, 'settled')}
												aria-label={`Settle ${thread.title ?? 'thread'}`}
												data-tooltip="Settle"
												onclick={() => void change(thread, 'settled')}><Check size={14} /></button
											>
										{:else}
											<button
												class="inbox-icon inbox-row-state-action"
												type="button"
												disabled={!mutationsEnabled || busy}
												aria-label={`Unsettle ${thread.title ?? 'thread'}`}
												data-tooltip="Unsettle"
												onclick={() => void change(thread, 'unsettled')}
												><RotateCcw size={14} /></button
											>
										{/if}
									</div>{/if}
							</div>
						{/each}
						<InboxLoadMore {section} />
					{/if}
				</div>
			</section>
		{/each}
	</div>

	{#if notice}
		<div class="inbox-notice" role="status">
			<span>{notice}</span>
			<button type="button" aria-label="Dismiss notification" onclick={() => (notice = null)}
				><X size={13} /></button
			>
		</div>
	{/if}

	<footer class="inbox-footer">
		<button class="inbox-menu-item inbox-primary-navigation" type="button" onclick={onSettings}>
			<Settings size={15} />Settings
		</button>
		<AppUpdate />
	</footer>
</aside>

{#if menu}
	{@const thread = menu.thread}
	<button
		class="fixed inset-0 z-[200] cursor-default"
		type="button"
		aria-label="Close thread actions"
		onclick={closeMenu}
	></button>
	<div
		class="inbox-context-menu"
		style:left={`${Math.max(8, menu.x)}px`}
		style:top={`${Math.max(8, menu.y)}px`}
		role="menu"
		tabindex="-1"
		onkeydown={navigateMenu}
	>
		{#if inboxState(thread) === 'unsettled'}
			<button
				type="button"
				role="menuitem"
				disabled={!mutationsEnabled || busy || !canChange(thread, 'settled')}
				onclick={() => void change(thread, 'settled')}><Check size={14} />Settle</button
			>
		{:else}
			<button
				type="button"
				role="menuitem"
				disabled={!mutationsEnabled || busy}
				onclick={() => void change(thread, 'unsettled')}><RotateCcw size={14} />Unsettle</button
			>
		{/if}
		<button
			type="button"
			role="menuitem"
			disabled={!mutationsEnabled}
			onclick={() => beginRename(thread)}><SquarePen size={14} />Rename</button
		>
		<button
			type="button"
			role="menuitem"
			onclick={() => {
				void navigator.clipboard.writeText(thread._id).catch(() => {
					notice = 'Could not copy thread ID.';
				});
				menu = null;
			}}><Copy size={14} />Copy thread ID</button
		>
	</div>
{/if}
