// apps/web/src/lib/components/home/thread-transcript.tsx
import {
	useCallback,
	useLayoutEffect,
	useRef,
	useState,
	type KeyboardEvent,
	type ReactNode
} from 'react';
import {
	assistantTimelinePartKey,
	buildAssistantTimeline,
	buildCommandSessionCommandMap,
	groupAssistantTimeline,
	groupAssistantTimelineSections,
	isAssistantResponseStreaming,
	partitionWorkSectionTools,
	workSectionTimingAnchor,
	type AssistantTimelineTool,
	type AssistantTimelineWorkBlock
} from '$lib/chat/assistant-timeline';
import { TranscriptSectionKeys } from '$lib/chat/transcript-section-keys';
import ChatMarkdown from '$lib/components/chat-markdown';
import ImageViewer, { type ViewerImage } from '$lib/components/image-viewer';
import TranscriptPromptMessage from '$lib/components/home/transcript-prompt-message';
import MandateApprovalForm from '$lib/components/home/mandate-approval-form';
import ReasoningDisclosure from '$lib/components/home/reasoning-disclosure';
import WorkTools from '$lib/components/home/work-tools';
import WorkDisclosure from '$lib/components/home/work-disclosure';
import WorkSectionDetails from '$lib/components/home/work-section-details';
import type {
	TranscriptDisplayRow,
	TranscriptDisplayDetails,
	TranscriptDetailCursor,
	LiveTranscriptMessage
} from '$lib/types/sprocket';
import { mandateApprovals } from '$lib/chat/mandate';
import type { ArtifactEntry } from '$lib/chat/artifacts';
import { formatElapsedDuration } from '$lib/format';
import type {
	ExecutorJob,
	TranscriptMessage,
	Project,
	MessageAttachment
} from '$lib/types/sprocket';
import '$lib/components/home/thread-transcript.css';

type Props = {
	currentError: string | null;
	runError: string | null;
	messages: TranscriptMessage[];
	actions: ExecutorJob[];
	activeRunId: TranscriptMessage['runId'] | null;
	project: Project | null;
	emptyStateMessage?: string;
	stale?: boolean;
	loadingOlder?: boolean;
	nextBefore?: number;
	onLoadOlder?: () => void;
	loadAttachment?: (storageId: MessageAttachment['storageId']) => Promise<string | null>;
	loadSectionDetails?: (
		row: TranscriptDisplayRow,
		cursor: TranscriptDetailCursor,
		signal: AbortSignal
	) => Promise<TranscriptDisplayDetails>;
	artifacts?: ArtifactEntry[];
	onOpenArtifact?: (artifactId: string) => void;
};

const SCROLL_EPSILON_PX = 28;

const HISTORY_PREFETCH_VIEWPORTS = 3;

const HISTORY_PREFETCH_PAGES = 3;

type ScrollAnchor = {
	anchor: HTMLElement;
	offset: number;
	scrollTop: number;
	scrollHeight: number;
};

function isArtifactToolGroup(block: AssistantTimelineWorkBlock) {
	return (
		block.type === 'tool-group' &&
		(block.toolKey === 'add_artifact' ||
			block.toolKey === 'list_artifacts' ||
			block.toolKey === 'edit_artifact' ||
			block.toolKey === 'create_artifact' ||
			block.toolKey === 'update_artifact')
	);
}

function isVisibleWorkBlock(block: AssistantTimelineWorkBlock) {
	return !isArtifactToolGroup(block);
}

function earlierTimestamp(left: number | undefined, right: number | undefined) {
	if (left === undefined) return right;

	if (right === undefined) return left;

	return Math.min(left, right);
}

function laterTimestamp(left: number | undefined, right: number | undefined) {
	if (left === undefined) return right;

	if (right === undefined) return left;

	return Math.max(left, right);
}

export default function ThreadTranscript({
	currentError,
	runError,
	messages,
	actions,
	activeRunId,
	project,
	emptyStateMessage = project
		? 'Start a thread and ask Sprocket to inspect code, edit files, or run project commands.'
		: 'Add a project to begin.',
	stale = false,
	loadingOlder = false,
	nextBefore,
	onLoadOlder,
	loadAttachment,
	loadSectionDetails,
	artifacts = [],
	onOpenArtifact
}: Props) {
	const viewportRef = useRef<HTMLDivElement | null>(null);
	const contentRef = useRef<HTMLDivElement | null>(null);
	const [viewport, setViewport] = useState<HTMLDivElement | null>(null);
	const stickToBottomRef = useRef(true);
	const lastScrollTopRef = useRef(0);
	const touchYRef = useRef<number | undefined>(undefined);
	const requestedBeforeRef = useRef<number | undefined>(undefined);
	const historyPrefetchPagesRef = useRef(HISTORY_PREFETCH_PAGES);
	const [viewerImage, setViewerImage] = useState<ViewerImage | null>(null);
	const [copiedMessageId, setCopiedMessageId] = useState<string | null>(null);
	const copiedTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
	const imageScope = project ? { workspacePath: project.workspacePath } : undefined;

	const sectionKeysRef = useRef<TranscriptSectionKeys | null>(null);

	if (!sectionKeysRef.current) sectionKeysRef.current = new TranscriptSectionKeys();
	const sectionKeys = sectionKeysRef.current;

	type LiveRenderState = ReturnType<typeof liveRenderState>;

	type LiveSection = ReturnType<TranscriptSectionKeys['reconcile']>[number];

	type LiveWorkState = ReturnType<typeof liveWorkState>;

	function liveRenderState(message: LiveTranscriptMessage) {
		const messageActions = actions.filter(
			(job) =>
				job.runId === message.runId &&
				message.parts.some((part) => part.type === 'tool-call' && part.callId === job.callId)
		);

		const timeline = buildAssistantTimeline(message.parts, messageActions);
		const tools = timeline.filter((item): item is AssistantTimelineTool => item.type === 'tool');

		const sections = sectionKeys.reconcile(
			message.id,
			groupAssistantTimelineSections(groupAssistantTimeline(timeline))
		);

		const isStreaming = isAssistantResponseStreaming(message, activeRunId);

		return {
			timeline,
			sections,
			isStreaming,
			commands: buildCommandSessionCommandMap(tools)
		};
	}

	function liveWorkState(
		state: LiveRenderState,
		section: Extract<LiveSection, { type: 'work' }>,
		sectionIndex: number
	) {
		const { settledBlocks, runningTools } = partitionWorkSectionTools(
			section.blocks,
			state.isStreaming
		);

		const visibleBlocks = settledBlocks.filter(isVisibleWorkBlock);

		const workInProgress =
			state.isStreaming && (sectionIndex === state.sections.length - 1 || runningTools.length > 0);

		const nextSection = state.sections[sectionIndex + 1];

		return {
			visibleBlocks,
			lastBlock: section.blocks.at(-1),
			runningTools,
			workInProgress,
			approvals: visibleBlocks.flatMap((block) =>
				block.type === 'tool-group' ? mandateApprovals(block.tools) : []
			),
			timing: workSectionTimingAnchor(section, {
				inProgress: workInProgress,
				endedAt: nextSection?.type === 'text' ? (nextSection.startedAt ?? undefined) : undefined
			})
		};
	}

	function followingLiveState(messageIndex: number, runId: TranscriptDisplayRow['runId']) {
		for (const message of messages.slice(messageIndex + 1)) {
			if (message.kind === 'approval' && message.runId === runId) continue;

			return message.kind === 'live' && message.runId === runId
				? liveRenderState(message)
				: undefined;
		}

		return undefined;
	}

	function followsOpenPersistedWork(messageIndex: number, runId: LiveTranscriptMessage['runId']) {
		for (let index = messageIndex - 1; index >= 0; index -= 1) {
			const message = messages[index];

			if (message.kind === 'approval' && message.runId === runId) continue;

			return message.kind === 'work' && message.runId === runId && !message.closed;
		}

		return false;
	}

	function firstVisibleAnchor(root: HTMLDivElement) {
		const elements = [
			...root.querySelectorAll<HTMLElement>('[data-transcript-anchor], [data-work-detail]')
		].filter((element) => !element.querySelector('[data-work-detail]'));

		const top = root.getBoundingClientRect().top;
		let low = 0;
		let high = elements.length;

		while (low < high) {
			const mid = Math.floor((low + high) / 2);

			if (elements[mid].getBoundingClientRect().bottom <= top) low = mid + 1;
			else high = mid;
		}

		return elements[low];
	}

	function setScrollTop(root: HTMLDivElement, top: number) {
		if (root.scrollTop !== top) root.scrollTop = top;
		lastScrollTopRef.current = root.scrollTop;
	}

	function scrollToBottom() {
		const root = viewportRef.current;

		if (!root || !stickToBottomRef.current) {
			return;
		}

		const bottom = Math.max(0, root.scrollHeight - root.clientHeight);

		// A scrollbar drag can reach layout before its scroll event. Shrinking content also clamps scrollTop.
		if (root.scrollTop + 1 < Math.min(lastScrollTopRef.current, bottom)) {
			stickToBottomRef.current = false;

			return;
		}

		setScrollTop(root, bottom);
	}

	function prefetchOlderHistory() {
		const root = viewportRef.current;

		if (
			root &&
			nextBefore !== undefined &&
			nextBefore !== requestedBeforeRef.current &&
			!loadingOlder &&
			onLoadOlder &&
			historyPrefetchPagesRef.current > 0 &&
			root.clientHeight > 0 &&
			root.scrollTop <= root.clientHeight * HISTORY_PREFETCH_VIEWPORTS
		) {
			historyPrefetchPagesRef.current -= 1;
			requestedBeforeRef.current = nextBefore;
			onLoadOlder();
		}
	}

	function stopFollowing() {
		stickToBottomRef.current = false;
		historyPrefetchPagesRef.current = HISTORY_PREFETCH_PAGES;
		prefetchOlderHistory();
	}

	function updateStickToBottom() {
		const root = viewportRef.current;

		if (!root) return;

		if (root.scrollTop === lastScrollTopRef.current) {
			prefetchOlderHistory();

			return;
		}

		const bottom = Math.max(0, root.scrollHeight - root.clientHeight);
		const movingUp = root.scrollTop < lastScrollTopRef.current;

		const clampedToBottom =
			lastScrollTopRef.current > bottom && Math.abs(root.scrollTop - bottom) < 1;

		lastScrollTopRef.current = root.scrollTop;
		historyPrefetchPagesRef.current = HISTORY_PREFETCH_PAGES;

		// A shorter scroll range must preserve the reader's existing follow state.
		if (!clampedToBottom) {
			const distanceToBottom = bottom - root.scrollTop;
			stickToBottomRef.current = !movingUp && distanceToBottom <= SCROLL_EPSILON_PX;

			if (movingUp) stopFollowing();
		}

		prefetchOlderHistory();
	}

	function handleHistoryKey(event: KeyboardEvent) {
		if (
			event.target instanceof Element &&
			event.target.closest('input, textarea, button, [contenteditable="true"]')
		) {
			return;
		}

		if (
			event.key === 'ArrowUp' ||
			event.key === 'PageUp' ||
			event.key === 'Home' ||
			(event.key === ' ' && event.shiftKey)
		) {
			stopFollowing();
		}
	}

	function beforeDetailChange(follow: boolean) {
		if (!follow) stickToBottomRef.current = false;
		const root = viewportRef.current;
		const anchor = root && !stickToBottomRef.current ? firstVisibleAnchor(root) : undefined;
		const offset = anchor?.getBoundingClientRect().top;
		const top = root?.scrollTop;

		return () => {
			if (!root || root !== viewportRef.current) return;

			if (stickToBottomRef.current) scrollToBottom();
			else if (anchor?.isConnected && offset !== undefined && root.scrollTop === top) {
				setScrollTop(root, root.scrollTop + anchor.getBoundingClientRect().top - offset);
			}
		};
	}

	const scrollToBottomRef = useRef(scrollToBottom);
	const prefetchOlderHistoryRef = useRef(prefetchOlderHistory);
	useLayoutEffect(() => {
		scrollToBottomRef.current = scrollToBottom;
		prefetchOlderHistoryRef.current = prefetchOlderHistory;
	});

	useLayoutEffect(() => {
		prefetchOlderHistoryRef.current();
	}, [messages, nextBefore, loadingOlder, viewport]);

	useLayoutEffect(() => {
		const root = viewport;
		const content = contentRef.current;

		if (!root || !content || !globalThis.ResizeObserver) {
			return;
		}

		const observer = new ResizeObserver(() => {
			scrollToBottomRef.current();
			prefetchOlderHistoryRef.current();
		});

		observer.observe(root);
		observer.observe(content);

		return () => {
			observer.disconnect();
		};
	}, [viewport]);

	// Anchor capture must read the DOM before this render commits, matching `$effect.pre`.
	const renderedMessagesRef = useRef(messages);
	const renderedActionsRef = useRef(actions);
	const anchorRef = useRef<ScrollAnchor | null>(null);

	if (renderedMessagesRef.current !== messages || renderedActionsRef.current !== actions) {
		renderedMessagesRef.current = messages;
		renderedActionsRef.current = actions;
		const root = viewportRef.current;
		const anchor = root && !stickToBottomRef.current ? firstVisibleAnchor(root) : undefined;
		anchorRef.current =
			root && anchor
				? {
						anchor,
						offset: anchor.getBoundingClientRect().top,
						scrollTop: root.scrollTop,
						scrollHeight: root.scrollHeight
					}
				: null;
	}

	useLayoutEffect(() => {
		const root = viewportRef.current;

		if (!root) return;

		if (stickToBottomRef.current) {
			scrollToBottomRef.current();

			return;
		}

		const snapshot = anchorRef.current;
		anchorRef.current = null;

		if (!snapshot) return;
		const { anchor, offset, scrollTop, scrollHeight } = snapshot;

		if (anchor.isConnected && root.scrollTop === scrollTop) {
			setScrollTop(root, scrollTop + anchor.getBoundingClientRect().top - offset);
		} else if (!anchor.isConnected && root.scrollTop === scrollTop) {
			setScrollTop(root, scrollTop + root.scrollHeight - scrollHeight);
		}
	}, [messages, actions]);

	async function copyUserMessage(messageId: string, text: string) {
		try {
			await navigator.clipboard.writeText(text);
			setCopiedMessageId(messageId);

			if (copiedTimeoutRef.current !== null) clearTimeout(copiedTimeoutRef.current);
			copiedTimeoutRef.current = setTimeout(() => {
				setCopiedMessageId((current) => (current === messageId ? null : current));
				copiedTimeoutRef.current = null;
			}, 1_500);
		} catch {
			setCopiedMessageId(null);
		}
	}

	useLayoutEffect(() => {
		return () => {
			if (copiedTimeoutRef.current !== null) clearTimeout(copiedTimeoutRef.current);
		};
	}, []);

	useLayoutEffect(() => {
		sectionKeys.retain(
			messages.filter((message) => message.kind === 'live').map((message) => message.id)
		);
	}, [messages, sectionKeys]);

	const setViewportNode = useCallback((node: HTMLDivElement | null) => {
		viewportRef.current = node;
		setViewport(node);
	}, []);

	function renderWorkBlocks(work: LiveWorkState, state: LiveRenderState) {
		return work.visibleBlocks.map((block, blockIndex) => {
			const renderKey = `${block.type}-${
				block.type === 'tool-group' ? block.tools.map((tool) => tool.callId).join(',') : block.id
			}-${blockIndex}`;

			if (block.type === 'reasoning') {
				const reasoningInProgress =
					work.workInProgress && work.runningTools.length === 0 && block === work.lastBlock;

				return (
					<ReasoningDisclosure key={renderKey} text={block.text} inProgress={reasoningInProgress} />
				);
			}

			return (
				<WorkTools
					key={renderKey}
					tools={block.tools}
					toolKey={block.toolKey}
					inProgress={state.isStreaming}
					commands={state.commands}
				/>
			);
		});
	}

	function renderMessage(message: TranscriptMessage, messageIndex: number): ReactNode {
		if (message.kind === 'prompt') {
			return (
				<TranscriptPromptMessage
					key={message.id}
					message={message}
					imageScope={imageScope}
					copied={copiedMessageId === message.id}
					loadAttachment={loadAttachment}
					onCopy={() => void copyUserMessage(message.id, message.text ?? '')}
					onOpenImage={setViewerImage}
				/>
			);
		}

		if (message.kind === 'work') {
			const row = message;
			const followingLive = !row.closed ? followingLiveState(messageIndex, row.runId) : undefined;
			const firstLiveSection = followingLive?.sections[0];

			const continuation =
				followingLive && firstLiveSection?.type === 'work'
					? liveWorkState(followingLive, firstLiveSection, 0)
					: undefined;

			const inProgress = continuation
				? continuation.workInProgress
				: firstLiveSection?.type === 'text'
					? false
					: row.runId === activeRunId && (!row.closed || row.pendingTools > 0);

			const startedAt = earlierTimestamp(row.startedAt, continuation?.timing.startedAtMs);

			const completedAt = laterTimestamp(
				row.completedAt,
				continuation?.timing.completedAtMs ??
					(firstLiveSection?.type === 'text'
						? (firstLiveSection.startedAt ?? undefined)
						: undefined)
			);

			return (
				<div
					key={message.id}
					data-message-id={message.id}
					data-transcript-anchor={message.id}
					data-message-kind="work"
				>
					<WorkDisclosure
						inProgress={inProgress}
						startedAtMs={startedAt}
						completedAtMs={completedAt}
					>
						{loadSectionDetails ? (
							<WorkSectionDetails
								row={row}
								load={loadSectionDetails}
								inProgress={inProgress}
								viewport={viewport}
								beforeChange={beforeDetailChange}
							/>
						) : null}
						{continuation && followingLive ? renderWorkBlocks(continuation, followingLive) : null}
					</WorkDisclosure>
				</div>
			);
		}

		if (message.kind === 'approval') {
			if (!message.mandateId || !message.approvalUrl) return null;

			return (
				<div key={message.id} data-transcript-anchor={message.id}>
					<MandateApprovalForm
						approval={{ mandateId: message.mandateId, approvalUrl: message.approvalUrl }}
					/>
				</div>
			);
		}

		if (message.kind === 'text') {
			return (
				<div
					key={message.id}
					data-message-id={message.id}
					data-transcript-anchor={message.id}
					data-message-kind="text"
				>
					<ChatMarkdown
						imageScope={imageScope}
						content={message.text || ' '}
						className="text-foreground"
						artifacts={artifacts}
						onOpenArtifact={onOpenArtifact}
						openLinksInNewTab
					/>
				</div>
			);
		}

		if (message.kind !== 'live') return null;

		const live = liveRenderState(message);
		const continuesPreviousWork = followsOpenPersistedWork(messageIndex, message.runId);

		const hasPersistedAssistantContent = live.timeline.some(
			(part) => part.type === 'text' || part.type === 'reasoning'
		);

		return (
			<div
				key={message.id}
				data-message-id={message.id}
				className="w-full min-w-0"
				role={live.isStreaming ? 'log' : undefined}
				aria-live={live.isStreaming ? 'polite' : undefined}
				aria-atomic="false"
				aria-relevant="additions text"
			>
				<div className="space-y-3">
					{!hasPersistedAssistantContent &&
					(message.text || (live.isStreaming && live.timeline.length === 0)) ? (
						<ChatMarkdown
							imageScope={imageScope}
							content={message.text || '...'}
							className="text-foreground"
							artifacts={artifacts}
							onOpenArtifact={onOpenArtifact}
							openLinksInNewTab
						/>
					) : null}
					{live.sections.map((section, sectionIndex) => {
						if (section.type === 'text') {
							return (
								<div
									key={section.renderKey}
									data-transcript-anchor={`${message.id}:${assistantTimelinePartKey(section)}`}
								>
									<ChatMarkdown
										imageScope={imageScope}
										content={section.text || ' '}
										className="text-foreground"
										artifacts={artifacts}
										onOpenArtifact={onOpenArtifact}
										openLinksInNewTab
									/>
								</div>
							);
						}

						const work = liveWorkState(live, section, sectionIndex);

						if (
							work.visibleBlocks.length === 0 &&
							!work.workInProgress &&
							work.runningTools.length === 0
						) {
							return null;
						}

						return (
							<div
								key={section.renderKey}
								className="space-y-3"
								data-transcript-anchor={`${message.id}:${section.renderKey}`}
							>
								{!(continuesPreviousWork && sectionIndex === 0) ? (
									<WorkDisclosure
										inProgress={work.workInProgress}
										startedAtMs={work.timing.startedAtMs}
										completedAtMs={work.timing.completedAtMs}
									>
										{renderWorkBlocks(work, live)}
									</WorkDisclosure>
								) : null}
								{work.approvals.map((approval) => (
									<MandateApprovalForm key={approval.mandateId} approval={approval} />
								))}
								{work.runningTools.length > 0 ? (
									<WorkTools
										tools={work.runningTools}
										running
										inProgress={live.isStreaming}
										commands={live.commands}
									/>
								) : null}
							</div>
						);
					})}
					{!live.isStreaming && message.runStartedAt > 0 && message.runCompletedAt !== undefined ? (
						<p className="text-muted-foreground text-sm">
							{`Worked for ${formatElapsedDuration(
								Math.max(0, Math.floor((message.runCompletedAt - message.runStartedAt) / 1000))
							)}`}
						</p>
					) : null}
				</div>
			</div>
		);
	}

	return (
		<div className="relative min-h-0 flex-1">
			<div
				className="hide-scrollbar h-full overflow-x-hidden overflow-y-auto"
				role="region"
				aria-label="Conversation history"
				tabIndex={0}
				ref={setViewportNode}
				onScroll={updateStickToBottom}
				onWheel={(event) => {
					if (event.deltaY < 0) stopFollowing();
				}}
				onKeyDown={handleHistoryKey}
				onTouchStart={(event) => {
					touchYRef.current = event.touches[0]?.clientY;
				}}
				onTouchMove={(event) => {
					const nextY = event.touches[0]?.clientY;

					if (nextY !== undefined && touchYRef.current !== undefined && nextY > touchYRef.current) {
						stopFollowing();
					}

					touchYRef.current = nextY;
				}}
			>
				<div
					ref={contentRef}
					className="mx-auto flex min-h-full w-full max-w-[48rem] flex-col px-4 py-8"
				>
					{currentError ? (
						<div
							role="alert"
							className="text-destructive mb-6 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm"
						>
							{currentError}
						</div>
					) : null}

					{runError ? (
						<div
							role="alert"
							className="mb-6 rounded-2xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200"
						>
							{runError}
						</div>
					) : null}

					{stale ? (
						<div
							role="status"
							className="mb-6 rounded-2xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200"
						>
							Reconnecting to conversation history.
						</div>
					) : null}

					{messages.length === 0 ? (
						emptyStateMessage ? (
							<div className="flex flex-1 items-center justify-center">
								<div className="max-w-2xl text-center">
									<p className="text-muted-foreground text-sm leading-7">{emptyStateMessage}</p>
								</div>
							</div>
						) : null
					) : (
						<div className="transcript-messages space-y-8 pb-14">
							{messages.map((message, messageIndex) => renderMessage(message, messageIndex))}
						</div>
					)}
				</div>
			</div>

			<div className="transcript-fade pointer-events-none absolute inset-x-0 bottom-0 h-16"></div>
			<ImageViewer image={viewerImage} onClose={() => setViewerImage(null)} />
		</div>
	);
}

// apps/web/src/lib/components/home/thread-transcript.svelte
<script lang="ts">
	import { Check, Copy, LoaderCircle } from '@lucide/svelte';
	import { tick, untrack } from 'svelte';
	import {
		assistantTimelineToolError,
		assistantTimelineToolFailureKind,
		assistantTimelinePartKey,
		buildAssistantTimeline,
		buildCommandSessionCommandMap,
		buildOpenExecCommandSessions,
		groupAssistantTimeline,
		groupAssistantTimelineSections,
		isAssistantResponseStreaming,
		partitionWorkSectionTools,
		workSectionTimingAnchor,
		type AssistantTimelineTool,
		type AssistantTimelineWorkBlock
	} from '$lib/chat/assistant-timeline';
	import { toolKindIcon, toolLogIcon } from '$lib/chat/tool-icons';
	import { TranscriptSectionKeys } from '$lib/chat/transcript-section-keys';
	import {
		changedFileCount,
		fullToolSummary,
		toolGroupLabel,
		toolItemSummary,
		toolSummaryClass
	} from '$lib/chat/tool-summaries';
	import ChatMarkdown from '$lib/components/chat-markdown.svelte';
	import ImageViewer, { type ViewerImage } from '$lib/components/image-viewer.svelte';
	import TranscriptAttachment from '$lib/components/home/transcript-attachment.svelte';
	import MandateApprovalForm from '$lib/components/home/mandate-approval-form.svelte';
	import ReasoningDisclosure from '$lib/components/home/reasoning-disclosure.svelte';
	import ToolCallsDisclosure from '$lib/components/home/tool-calls-disclosure.svelte';
	import WorkDisclosure from '$lib/components/home/work-disclosure.svelte';
	import { mandateApprovals } from '$lib/chat/mandate';
	import { formatElapsedDuration } from '$lib/format';
	import type { ExecutorJob, ThreadMessage, Project, MessageAttachment } from '$lib/types/sprocket';

	type Props = {
		currentError: string | null;
		runError: string | null;
		messages: ThreadMessage[];
		actions: ExecutorJob[];
		activeRunId: ThreadMessage['runId'] | null;
		project: Project | null;
		remoteChangeNotice?: string | null;
		onDismissRemoteChangeNotice?: () => void;
		emptyStateMessage?: string;
		stale?: boolean;
		loadingOlder?: boolean;
		nextBefore?: number;
		onLoadOlder?: () => void;
		loadAttachment?: (storageId: MessageAttachment['storageId']) => Promise<string | null>;
		onLoadDetails?: (message: ThreadMessage) => Promise<void>;
	};

	let {
		currentError,
		runError,
		messages,
		actions,
		activeRunId,
		project,
		remoteChangeNotice = null,
		onDismissRemoteChangeNotice,
		emptyStateMessage = project
			? 'Start a thread and ask Sprocket to inspect code, edit files, or run project commands.'
			: 'Add a project to begin.',
		stale = false,
		loadingOlder = false,
		nextBefore,
		onLoadOlder,
		loadAttachment,
		onLoadDetails
	}: Props = $props();
	const firstPromptMessageId = $derived(messages.find((message) => message.type === 'prompt')?._id);
	let scrollViewport = $state<HTMLDivElement | null>(null);
	let scrollContent = $state<HTMLDivElement | null>(null);
	let stickToBottom = $state(true);
	let lastScrollTop = 0;
	let touchY: number | undefined;
	let automaticPagesRemaining = 2;
	let lastAutomaticBefore: number | undefined;

	const SCROLL_EPSILON_PX = 28;

	function updateStickToBottom() {
		const viewport = scrollViewport;
		if (!viewport || viewport.scrollTop === lastScrollTop) return;
		const bottom = Math.max(0, viewport.scrollHeight - viewport.clientHeight);
		const movingUp = viewport.scrollTop < Math.min(lastScrollTop, bottom);
		lastScrollTop = viewport.scrollTop;
		const distanceToBottom = bottom - viewport.scrollTop;
		stickToBottom = !movingUp && distanceToBottom <= SCROLL_EPSILON_PX;
		if (movingUp) handleUpwardIntent();
	}

	function handleUpwardIntent() {
		stickToBottom = false;
		const viewport = scrollViewport;
		if (
			viewport &&
			nextBefore !== undefined &&
			!loadingOlder &&
			viewport.clientHeight > 0 &&
			viewport.scrollTop <= viewport.clientHeight
		) {
			onLoadOlder?.();
		}
	}

	function fillViewport() {
		const viewport = scrollViewport;
		if (
			viewport &&
			nextBefore !== undefined &&
			nextBefore !== lastAutomaticBefore &&
			!loadingOlder &&
			onLoadOlder &&
			automaticPagesRemaining > 0 &&
			viewport.clientHeight > 0 &&
			viewport.scrollHeight <= viewport.clientHeight + SCROLL_EPSILON_PX
		) {
			// Collapsed work can consume many pages without making the viewport taller.
			automaticPagesRemaining -= 1;
			lastAutomaticBefore = nextBefore;
			onLoadOlder();
		}
	}

	$effect(() => {
		void messages;
		void nextBefore;
		void loadingOlder;
		void scrollViewport;
		untrack(fillViewport);
	});

	function handleHistoryKey(event: KeyboardEvent) {
		if (
			event.target instanceof Element &&
			event.target.closest('input, textarea, button, [contenteditable="true"]')
		) {
			return;
		}
		if (
			event.key === 'ArrowUp' ||
			event.key === 'PageUp' ||
			event.key === 'Home' ||
			(event.key === ' ' && event.shiftKey)
		) {
			handleUpwardIntent();
		}
	}

	function isArtifactToolGroup(
		block: AssistantTimelineWorkBlock
	): block is Extract<AssistantTimelineWorkBlock, { type: 'tool-group' }> {
		return (
			block.type === 'tool-group' &&
			(block.toolKey === 'add_artifact' ||
				block.toolKey === 'list_artifacts' ||
				block.toolKey === 'edit_artifact' ||
				block.toolKey === 'create_artifact' ||
				block.toolKey === 'update_artifact')
		);
	}

	function isVisibleWorkBlock(block: AssistantTimelineWorkBlock): boolean {
		return !isArtifactToolGroup(block);
	}

	const sectionKeys = new TranscriptSectionKeys();
	$effect.pre(() => sectionKeys.retain(messages.map((message) => message._id)));

	const userMessageClass =
		'user-bubble w-fit max-w-[33rem] rounded-xl border px-5 py-3.5 text-[15.5px] leading-7 text-foreground';

	let viewerImage = $state<ViewerImage | null>(null);

	let copiedMessageId = $state<string | null>(null);
	let copiedTimeout: ReturnType<typeof setTimeout> | null = null;

	async function copyUserMessage(messageId: string, text: string) {
		try {
			await navigator.clipboard.writeText(text);
			copiedMessageId = messageId;
			if (copiedTimeout !== null) {
				clearTimeout(copiedTimeout);
			}
			copiedTimeout = setTimeout(() => {
				if (copiedMessageId === messageId) {
					copiedMessageId = null;
				}
				copiedTimeout = null;
			}, 1_500);
		} catch {
			copiedMessageId = null;
		}
	}

	$effect(() => {
		return () => {
			if (copiedTimeout !== null) {
				clearTimeout(copiedTimeout);
			}
		};
	});

	function scrollToBottom() {
		const viewport = scrollViewport;
		if (!viewport || !stickToBottom) {
			return;
		}
		const bottom = Math.max(0, viewport.scrollHeight - viewport.clientHeight);
		// A scrollbar drag can reach layout before its scroll event. Shrinking content also clamps scrollTop.
		if (viewport.scrollTop < Math.min(lastScrollTop, bottom)) {
			stickToBottom = false;
			return;
		}
		setScrollTop(viewport, bottom);
	}

	function setScrollTop(viewport: HTMLDivElement, top: number) {
		if (viewport.scrollTop !== top) viewport.scrollTop = top;
		lastScrollTop = viewport.scrollTop;
	}

	function firstVisibleAnchor(viewport: HTMLDivElement) {
		const elements = viewport.querySelectorAll<HTMLElement>('[data-transcript-anchor]');
		const top = viewport.getBoundingClientRect().top;
		let low = 0;
		let high = elements.length;
		while (low < high) {
			const mid = Math.floor((low + high) / 2);
			if (elements[mid].getBoundingClientRect().bottom <= top) low = mid + 1;
			else high = mid;
		}
		return elements[low];
	}

	$effect.pre(() => {
		void messages;
		void actions;
		void scrollViewport;
		untrack(() => {
			const viewport = scrollViewport;
			if (!viewport) return;
			const anchor = stickToBottom ? undefined : firstVisibleAnchor(viewport);
			const offset = anchor?.getBoundingClientRect().top;
			const scrollTop = viewport.scrollTop;
			const scrollHeight = viewport.scrollHeight;
			void tick().then(() => {
				if (viewport !== scrollViewport) return;
				if (stickToBottom) {
					scrollToBottom();
				} else if (
					anchor?.isConnected &&
					offset !== undefined &&
					viewport.scrollTop === scrollTop
				) {
					setScrollTop(viewport, scrollTop + anchor.getBoundingClientRect().top - offset);
				} else if (anchor && !anchor.isConnected && viewport.scrollTop === scrollTop) {
					setScrollTop(viewport, scrollTop + viewport.scrollHeight - scrollHeight);
				}
			});
		});
	});

	$effect(() => {
		const viewport = scrollViewport;
		const content = scrollContent;
		if (!viewport || !content || !globalThis.ResizeObserver) {
			return;
		}

		const observer = new ResizeObserver(() => {
			scrollToBottom();
			fillViewport();
		});
		observer.observe(viewport);
		observer.observe(content);
		return () => {
			observer.disconnect();
		};
	});
</script>

<div class="relative min-h-0 flex-1">
	<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions (Keyboard users must be able to page history even when it does not overflow.) -->
	<div
		class="hide-scrollbar h-full overflow-auto"
		role="region"
		aria-label="Conversation history"
		tabindex="0"
		bind:this={scrollViewport}
		onscroll={updateStickToBottom}
		onwheel={(event) => {
			if (event.deltaY < 0) handleUpwardIntent();
		}}
		onkeydown={handleHistoryKey}
		ontouchstart={(event) => {
			touchY = event.touches[0]?.clientY;
		}}
		ontouchmove={(event) => {
			const nextY = event.touches[0]?.clientY;
			if (nextY !== undefined && touchY !== undefined && nextY > touchY) {
				handleUpwardIntent();
			}
			touchY = nextY;
		}}
	>
		<div
			bind:this={scrollContent}
			class="mx-auto flex min-h-full w-full max-w-5xl flex-col px-4 py-8"
		>
			{#if currentError}
				<div
					role="alert"
					class="text-destructive mb-6 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm"
				>
					{currentError}
				</div>
			{/if}

			{#if runError}
				<div
					role="alert"
					class="mb-6 rounded-2xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200"
				>
					{runError}
				</div>
			{/if}

			{#if stale}
				<div
					role="status"
					class="mb-6 rounded-2xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200"
				>
					Showing a local copy while Sprocket reconnects to history.
				</div>
			{/if}

			{#if messages.length === 0}
				{#if emptyStateMessage}
					<div class="flex flex-1 items-center justify-center">
						<div class="max-w-2xl text-center">
							<p class="text-muted-foreground text-sm leading-7">{emptyStateMessage}</p>
						</div>
					</div>
				{/if}
			{:else}
				<div class="space-y-8 pb-14">
					{#each messages as message (message._id)}
						{#if message.type === 'prompt'}
							<div
								data-message-id={message._id}
								data-transcript-anchor={message._id}
								class="flex flex-col items-end gap-1.5"
							>
								{#if message.attachments.length}
									<ul
										class="flex max-w-132 flex-wrap justify-end gap-2"
										aria-label="Attached files"
									>
										{#each message.attachments as attachment (attachment.storageId)}
											<li>
												<TranscriptAttachment
													{attachment}
													{loadAttachment}
													onOpen={(image) => {
														viewerImage = image;
													}}
												/>
											</li>
										{/each}
									</ul>
								{/if}
								{#if message.text || !message.attachments.length}
									<div class={userMessageClass}>
										<ChatMarkdown content={message.text || ' '} className="text-foreground" />
									</div>
								{/if}
								{#if message.text}
									<button
										type="button"
										class="text-muted-foreground hover:text-muted-foreground inline-flex size-6 items-center justify-center rounded-md transition"
										aria-label={copiedMessageId === message._id ? 'Copied' : 'Copy message'}
										onclick={() => {
											void copyUserMessage(message._id, message.text);
										}}
									>
										{#if copiedMessageId === message._id}
											<Check class="size-3.5" aria-hidden="true" />
										{:else}
											<Copy class="size-3.5" aria-hidden="true" />
										{/if}
									</button>
								{/if}
								{#if remoteChangeNotice && message._id === firstPromptMessageId}
									<div
										role="status"
										class="w-full max-w-132 rounded-2xl border border-amber-500/25 bg-amber-500/10 px-4 py-3 text-left text-sm text-amber-800 dark:text-amber-200"
									>
										<div class="flex items-start justify-between gap-3">
											<p class="min-w-0 flex-1 leading-6">{remoteChangeNotice}</p>
											{#if onDismissRemoteChangeNotice}
												<button
													type="button"
													class="shrink-0 text-xs font-medium tracking-[-0.01em] text-amber-800/80 underline-offset-2 hover:text-amber-900 hover:underline dark:text-amber-200/80 dark:hover:text-amber-100"
													onclick={onDismissRemoteChangeNotice}
												>
													Dismiss
												</button>
											{/if}
										</div>
									</div>
								{/if}
							</div>
						{:else}
							{@const messageActions = actions.filter((job) => job.runId === message.runId)}
							{@const timeline = buildAssistantTimeline(
								message.parts,
								messageActions,
								message.detailsLoaded !== false
							)}
							{@const timelineTools = timeline.filter(
								(item): item is AssistantTimelineTool => item.type === 'tool'
							)}
							{@const sessionCommands = buildCommandSessionCommandMap(timelineTools)}
							{@const blocks = groupAssistantTimeline(timeline)}
							{@const sections = sectionKeys.reconcile(
								message._id,
								groupAssistantTimelineSections(blocks)
							)}
							{@const isStreaming = isAssistantResponseStreaming(message, activeRunId)}
							{@const openSessions = buildOpenExecCommandSessions(timelineTools, isStreaming)}
							{@const hasPersistedAssistantContent = timeline.some(
								(part) => part.type === 'text' || part.type === 'reasoning'
							)}
							<div
								data-message-id={message._id}
								class="w-full min-w-0"
								role={isStreaming ? 'log' : undefined}
								aria-live={isStreaming ? 'polite' : undefined}
								aria-atomic="false"
								aria-relevant="additions text"
							>
								<div class="space-y-3">
									{#if !hasPersistedAssistantContent && (message.text || (isStreaming && timeline.length === 0))}
										<ChatMarkdown content={message.text || '...'} className="text-foreground" />
									{/if}
									{#each sections as section, sectionIndex (section.renderKey)}
										{#if section.type === 'text'}
											<div
												data-transcript-anchor={`${message._id}:${assistantTimelinePartKey(section)}`}
											>
												<ChatMarkdown content={section.text || ' '} className="text-foreground" />
											</div>
										{:else}
											{@const { settledBlocks, runningTools } = partitionWorkSectionTools(
												section.blocks,
												isStreaming,
												openSessions
											)}
											{@const visibleBlocks = settledBlocks.filter(isVisibleWorkBlock)}
											{@const sectionMandateApprovals = visibleBlocks.flatMap((block) =>
												block.type === 'tool-group' ? mandateApprovals(block.tools) : []
											)}
											{@const workInProgress =
												isStreaming &&
												(sectionIndex === sections.length - 1 || runningTools.length > 0)}
											{@const nextSection = sections[sectionIndex + 1]}
											{@const timing = workSectionTimingAnchor(section, {
												inProgress: workInProgress,
												endedAt:
													nextSection?.type === 'text'
														? (nextSection.startedAt ?? undefined)
														: undefined
											})}
											{#if visibleBlocks.length > 0 || workInProgress || runningTools.length > 0}
												<div
													class="space-y-3"
													data-transcript-anchor={`${message._id}:${section.renderKey}`}
												>
													<WorkDisclosure
														inProgress={workInProgress}
														startedAtMs={timing.startedAtMs}
														completedAtMs={timing.completedAtMs}
														detailsKey={`${message.sourceNumbers?.join(',')}:${message.detailsLoaded}`}
														onExpand={() => onLoadDetails?.(message)}
													>
														{#each visibleBlocks as block, blockIndex (`${block.type}-${block.type === 'tool-group' ? block.tools.map((tool) => tool.callId).join(',') : block.id}-${blockIndex}`)}
															{#if block.type === 'reasoning'}
																{@const reasoningInProgress =
																	workInProgress &&
																	runningTools.length === 0 &&
																	blockIndex === visibleBlocks.length - 1}
																<ReasoningDisclosure
																	text={block.text}
																	inProgress={reasoningInProgress}
																/>
															{:else}
																<ToolCallsDisclosure
																	label={toolGroupLabel(block.toolKey)}
																	icon={toolKindIcon(block.toolKey)}
																	tools={block.tools}
																	defaultExpanded={block.toolKey === 'apply_patch'
																		? changedFileCount(block.tools) <= 2
																		: undefined}
																>
																	{#snippet toolRow(tool)}
																		{@const toolError = assistantTimelineToolError(
																			tool,
																			isStreaming
																		)}
																		{@const toolFailureKind = assistantTimelineToolFailureKind(
																			tool,
																			isStreaming
																		)}
																		{@const toolSummary = toolItemSummary(tool, sessionCommands)}
																		{#if toolError && toolFailureKind}
																			<details class="min-w-0">
																				<summary
																					class="min-w-0 cursor-pointer text-left"
																					title={fullToolSummary(
																						tool,
																						isStreaming,
																						sessionCommands
																					)}
																				>
																					<span class={toolSummaryClass(tool)}>{toolSummary}</span>
																					<span
																						class={toolFailureKind === 'failed'
																							? 'text-destructive'
																							: 'text-amber-800 dark:text-amber-200'}
																					>
																						({toolFailureKind})
																					</span>
																				</summary>
																				<p
																					class="mt-1.5 text-xs leading-5 wrap-break-word whitespace-pre-wrap {toolFailureKind ===
																					'failed'
																						? 'text-destructive'
																						: 'text-amber-800 dark:text-amber-200'}"
																					role="status"
																				>
																					{toolError}
																				</p>
																			</details>
																		{:else}
																			<p
																				class={`min-w-0 ${toolSummaryClass(tool)}`}
																				title={fullToolSummary(tool, isStreaming, sessionCommands)}
																			>
																				{toolSummary}
																			</p>
																		{/if}
																	{/snippet}
																</ToolCallsDisclosure>
															{/if}
														{/each}
													</WorkDisclosure>
													{#each sectionMandateApprovals as approval (approval.mandateId)}
														<MandateApprovalForm {approval} />
													{/each}
													{#if runningTools.length > 0}
														<ToolCallsDisclosure
															label="Running"
															icon={LoaderCircle}
															iconClass="animate-spin"
															tools={runningTools}
															defaultExpanded={true}
														>
															{#snippet toolRow(tool)}
																{@const ToolIcon = toolLogIcon(tool)}
																{@const toolSummary = toolItemSummary(tool, sessionCommands)}
																<p
																	class="flex min-w-0 items-start gap-1.5"
																	title={`${toolSummary} (running)`}
																>
																	<ToolIcon
																		class="text-muted-foreground mt-1.5 size-3 shrink-0"
																		aria-hidden="true"
																	/>
																	<span class={toolSummaryClass(tool)}>{toolSummary}</span>
																</p>
															{/snippet}
														</ToolCallsDisclosure>
													{/if}
												</div>
											{/if}
										{/if}
									{/each}
									{#if !isStreaming && message.runStartedAt > 0 && message.runCompletedAt !== undefined}
										<p class="text-muted-foreground text-sm">
											Worked for {formatElapsedDuration(
												Math.max(
													0,
													Math.floor((message.runCompletedAt - message.runStartedAt) / 1000)
												)
											)}
										</p>
									{/if}
								</div>
							</div>
						{/if}
					{/each}
				</div>
			{/if}
		</div>
	</div>

	<div class="transcript-fade pointer-events-none absolute inset-x-0 bottom-0 h-16"></div>
</div>

<ImageViewer
	image={viewerImage}
	onClose={() => {
		viewerImage = null;
	}}
/>
